name: Test code style on PR

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-python-versions:
    runs-on: ubuntu-latest
    outputs:
      python-versions: ${{ steps.extract_python.outputs.python-versions }}
    steps:
      - uses: actions/checkout@v4

      - name: Get matrix
        id: get_matrix
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          module: ./.ci
          args: tests get-versions-matrix export --path=./matrix.json
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Extract Python versions
        id: extract_python
        run: |
          echo "python-versions=$(jq -c '.python' ./matrix.json)" >> $GITHUB_OUTPUT

  pre-commit:
    name: 'pre commit'
    needs: get-python-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJSON(needs.get-python-versions.outputs.python-versions) }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: pre-commit/action@v3.0.0

  ruff:
    name: 'ruff check'
    needs: get-python-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJSON(needs.get-python-versions.outputs.python-versions) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install ruff==0.3.7
      - run: ruff check

  mypy:
    name: 'mypy type check'
    needs: get-python-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJSON(needs.get-python-versions.outputs.python-versions) }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: uv sync --all-groups --all-extras
      - run: uv run mypy dmp_af --python-version=${{ matrix.python-version }} --show-error-codes
