name: Tests

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-python-versions:
    runs-on: ubuntu-latest
    outputs:
      python-versions: ${{ steps.extract_python.outputs.python-versions }}
    steps:
      - uses: actions/checkout@v4

      - name: Get matrix
        id: get_matrix
        uses: dagger/dagger-for-github@8.2.0
        with:
          version: ${{ vars.DAGGER_CORE_VERSION }}
          module: ./.ci
          args: tests get-versions-matrix export --path=./matrix.json
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Extract Python versions
        id: extract_python
        run: |
          echo "python-versions=$(jq -c '.python' ./matrix.json)" >> $GITHUB_OUTPUT

  test:
    needs: get-python-versions
    runs-on: [ ubuntu-latest ]
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJSON(needs.get-python-versions.outputs.python-versions) }}
    steps:
      - uses: actions/checkout@v4
      - name: Test airflow v2
        uses: dagger/dagger-for-github@8.2.0
        with:
          version: ${{ vars.DAGGER_CORE_VERSION }}
          module: ./.ci
          args: tests test-one-versions-combination --python-version=${{ matrix.python-version }} --airflow-version=2.11.0 --dbt-version=1.10 --with-running-airflow-tasks
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Test airflow v3
        uses: dagger/dagger-for-github@8.2.0
        with:
          version: ${{ vars.DAGGER_CORE_VERSION }}
          module: ./.ci
          args: tests test-one-versions-combination --python-version=${{ matrix.python-version }} --airflow-version=3.1.2 --dbt-version=1.10 --with-running-airflow-tasks
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
